server:
  port: 28082
spring:
  application:
    name:  zx-autodeliver # 应⽤名称，会在Eureka中作为服务的id标识（serviceId）
eureka:
  client:
    service-url: #客户端与EurekaServer交互的地址，如果是集群，也需要写其它Server的地址
      defaultZone:  http://zxeureka1.com:28761/eureka,http://zxeureka2.com:28762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@


zx-resume :
  ribbon:
    #请求连接超时时间
    ConnectTimeout: 2000
    #请求处理超时时间
    ##########################################Feign超时时长设置
    ReadTimeout: 1000
  level:
    com.zx.feignApi.HelloRemote

logging:
  level:
    com.zx.feignApi.HelloRemote : debug

feign:
  hystrix:
    enabled: true  #开启Feign的熔断功能

hystrix:
  command:
    default:
      execution:
        isolation:
            thread :
              ##########################################Hystrix的超时时⻓设置
              timeoutInMilliseconds: 4000
