server:
  port: 29000
eureka:
  client:
     serviceUrl: # eureka server的路径
          #把 eureka 集群中的所有 url 都填写了进来，也可以只写⼀台，因为各个 eureka server 可以同步注册表
          defaultZone: http://zxeureka1.com:28761/eureka,http://zxeureka2.com:28762/eureka
  instance:
  #使⽤ip注册，否则会使⽤主机名注册了（此处考虑到对⽼版本的兼容，新版本经过实验都是ip）
      prefer-ip-address: true
      #⾃定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
      instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
      name: gateway
  cloud:
    gateway:
        routes: # 路由可以有多个
          - id: zx-autodeliver # 我们⾃定义的路由 ID，保持唯⼀
          #⽬标服务地址 ⾃动投递微服务（部署多实例） 动态路由：uri配置的应该是⼀个服务名称，⽽不应该是⼀个具体的
          #服务实例的地址
            uri: lb://zx-autodeliver
          # gateway⽹关从服务注册中⼼获取实例信息然后负载后路由
            predicates: #断⾔：路由条件，Predicate 接受⼀个输⼊参数，返回⼀个布尔值结果。该接⼝包含
          #多种默 认⽅法来将 Predicate 组合成其他复杂的逻辑（⽐如：与，或，⾮）。
              - Path=/autodeliver/**
            filters :
#              - name : TokenGatewayFilterFactory
#                args :
#                   enabled : true
#            - Token=true
          - id: zx-resume # 我们⾃定义的路由 ID，保持唯⼀
            uri: lb://zx-resume # ⽬标服务地址
            predicates: #断⾔：路由条件，Predicate 接受⼀个输⼊参数，返回⼀个布尔值结果。该接⼝包含
            #多种默 认⽅法来将 Predicate 组合成其他复杂的逻辑（⽐如：与，或，⾮）。
              - Path=/resume/resume/**
            filters :
              - StripPrefix=1 # 可以去掉resume之后转发

